version: '3'
services:
      web:
       image:  node_app
       container_name: node_app
       restart: always
       command: "node server.js"
       ports:
         - '9000:5001'
       networks: 
        - node_net
      mongo:
          container_name: mongo
          image: mongo
          
          depends_on: 
            - web
          networks:
            - node_net
          ports:
            - '27017:27017'
networks:
  node_net:



